# Site settings
title: Free163.Com
username: Free163
email: Free163@Free163.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/"
url: "http://yourdomain.com"
aboutme: "归来卧松云，微凉送晚风。 枕上听松语，槛外看潮生!"
ads: /images/ads.jpg

# Build settings
markdown: kramdown
gems: [jekyll-paginate]
paginate: 3
paginate_path: "/page:num/"

# Comment thread setting
disqus_forumname: tranquil-theme